"""
Export endpoints for FIU-IND reporting.
"""

from io import BytesIO
from datetime import datetime, timezone
from typing import List, Tuple

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from ...core.security import rate_limiter, verify_api_key
from ...core.audit import audit_log
from ...core.auth import verify_investigator_access, AuthUser
from ...db.neo4j_client import get_driver
from .evidence import build_evidence_package, fetch_chain_nodes
from .schemas import FiuExportRequest

router = APIRouter(prefix="/api/v1/export", tags=["export"])


def _wrap_text(pdf: canvas.Canvas, text: str, max_width: float, font: str, size: int) -> List[str]:
    pdf.setFont(font, size)
    words = text.split()
    lines: List[str] = []
    current: List[str] = []
    for word in words:
        candidate = " ".join(current + [word])
        if pdf.stringWidth(candidate, font, size) <= max_width:
            current.append(word)
        else:
            if current:
                lines.append(" ".join(current))
            current = [word]
    if current:
        lines.append(" ".join(current))
    return lines


def _draw_header(pdf: canvas.Canvas, width: float, height: float, report_id: str) -> None:
    pdf.setFillColor(colors.HexColor("#0b1220"))
    pdf.rect(0, height - 90, width, 90, stroke=0, fill=1)
    pdf.setFillColor(colors.HexColor("#f8d15b"))
    pdf.rect(0, height - 92, width, 2, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(40, height - 55, "FIU-IND Suspicious Transaction Report (Draft)")
    pdf.setFont("Helvetica", 9)
    pdf.drawString(40, height - 73, f"Report ID: {report_id}")
    pdf.drawRightString(width - 40, height - 73, "Confidential • For Compliance Review")


def _draw_footer(pdf: canvas.Canvas, width: float) -> None:
    pdf.setStrokeColor(colors.HexColor("#22304a"))
    pdf.setLineWidth(0.5)
    pdf.line(40, 60, width - 40, 60)
    pdf.setFont("Helvetica", 8)
    pdf.setFillColor(colors.HexColor("#7a8699"))
    pdf.drawString(40, 45, "Generated by FundTrace AI Compliance Suite")
    pdf.drawRightString(width - 40, 45, "Page 1")


def _draw_section_title(pdf: canvas.Canvas, text: str, x: float, y: float) -> float:
    pdf.setFont("Helvetica-Bold", 11)
    pdf.setFillColor(colors.HexColor("#0b1220"))
    pdf.drawString(x, y, text)
    pdf.setStrokeColor(colors.HexColor("#d6b450"))
    pdf.setLineWidth(1)
    pdf.line(x, y - 6, x + 160, y - 6)
    return y - 18


def _draw_key_values(
    pdf: canvas.Canvas, items: List[Tuple[str, str]], x: float, y: float, max_width: float
) -> float:
    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.HexColor("#1d2638"))
    line_height = 14
    for label, value in items:
        pdf.setFont("Helvetica-Bold", 9)
        pdf.drawString(x, y, f"{label}:")
        pdf.setFont("Helvetica", 9)
        lines = _wrap_text(pdf, value, max_width - 120, "Helvetica", 9)
        if lines:
            pdf.drawString(x + 120, y, lines[0])
            for line in lines[1:]:
                y -= line_height
                pdf.drawString(x + 120, y, line)
        y -= line_height
    return y


def _draw_table(
    pdf: canvas.Canvas,
    headers: List[str],
    rows: List[List[str]],
    x: float,
    y: float,
    col_widths: List[int],
    max_rows: int = 12,
) -> float:
    pdf.setFillColor(colors.HexColor("#0b1220"))
    pdf.setFont("Helvetica-Bold", 9)
    row_height = 16
    pdf.rect(x, y - row_height, sum(col_widths), row_height, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    col_x = x
    for header, width in zip(headers, col_widths):
        pdf.drawString(col_x + 6, y - row_height + 4, header)
        col_x += width
    y -= row_height
    pdf.setFont("Helvetica", 8)
    for index, row in enumerate(rows[:max_rows]):
        if index % 2 == 0:
            pdf.setFillColor(colors.HexColor("#f2f4f8"))
            pdf.rect(x, y - row_height, sum(col_widths), row_height, stroke=0, fill=1)
        pdf.setFillColor(colors.HexColor("#1d2638"))
        col_x = x
        for cell, width in zip(row, col_widths):
            pdf.drawString(col_x + 6, y - row_height + 4, cell)
            col_x += width
        y -= row_height
    return y


@router.post(
    "/fiu-ind",
    dependencies=[Depends(verify_api_key), rate_limiter(limit=3, window_seconds=60)],
)
@audit_log(action_type="EXPORT_FIU_IND")
async def export_fiu_ind(
    payload: FiuExportRequest,
    current_user: AuthUser = Depends(verify_investigator_access),
) -> StreamingResponse:
    driver = get_driver()
    chain_nodes = fetch_chain_nodes(driver, payload.cluster_id)
    if not chain_nodes:
        raise HTTPException(status_code=404, detail=f"Transaction {payload.cluster_id} not found")
    evidence = build_evidence_package(chain_nodes, payload.cluster_id)

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    report_id = f"FIU-IND-{evidence.txId}"
    _draw_header(pdf, width, height, report_id)

    pdf.saveState()
    pdf.setFillColor(colors.HexColor("#0b1220"))
    pdf.setFont("Helvetica-Bold", 52)
    pdf.translate(width / 2, height / 2)
    pdf.rotate(30)
    pdf.setFillColor(colors.Color(0.8, 0.8, 0.8, alpha=0.08))
    pdf.drawCentredString(0, 0, "CONFIDENTIAL")
    pdf.restoreState()

    y = height - 120
    generated_at = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    max_score = max(evidence.risk_scores) if evidence.risk_scores else 0.0
    primary_pattern = (
        evidence.patterns[evidence.risk_scores.index(max_score)]
        if evidence.risk_scores
        else "Unknown"
    )
    high_risk = sum(1 for score in evidence.risk_scores if score >= 0.85)

    y = _draw_section_title(pdf, "Reporting Entity", 40, y)
    y = _draw_key_values(
        pdf,
        [
            ("Reporting Entity", "FundTrace AI (Demo Environment)"),
            ("Prepared By", "Automated Compliance Engine"),
            ("Generated At", generated_at),
            ("Report Type", "Suspicious Transaction Report (STR)"),
        ],
        40,
        y,
        width - 80,
    )

    y = _draw_section_title(pdf, "Case Summary", 40, y - 6)
    y = _draw_key_values(
        pdf,
        [
            ("Case / Transaction ID", evidence.txId),
            ("Total Hops", str(len(evidence.chain))),
            ("Primary Pattern", primary_pattern),
            ("Peak Risk Score", f"{max_score:.2f}"),
            ("High-Risk Nodes", str(high_risk)),
            ("Aggregate Amount", f"₹{evidence.total_amount:,.0f}"),
        ],
        40,
        y,
        width - 80,
    )

    y = _draw_section_title(pdf, "Narrative Summary", 40, y - 6)
    narrative_lines = _wrap_text(pdf, evidence.narrative, width - 80, "Helvetica", 9)
    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.HexColor("#1d2638"))
    for line in narrative_lines:
        pdf.drawString(40, y, line)
        y -= 12

    y -= 6
    y = _draw_section_title(pdf, "Transaction Chain", 40, y)
    chain_rows = []
    for idx, tx_id in enumerate(evidence.chain):
        score = evidence.risk_scores[idx] if idx < len(evidence.risk_scores) else 0.0
        pattern = evidence.patterns[idx] if idx < len(evidence.patterns) else "Unknown"
        chain_rows.append([str(idx + 1), tx_id[:24], f"{score:.2f}", pattern])

    y = _draw_table(
        pdf,
        headers=["Hop", "Transaction ID", "Risk", "Pattern"],
        rows=chain_rows,
        x=40,
        y=y,
        col_widths=[40, 240, 60, 160],
        max_rows=12,
    )

    if len(chain_rows) > 12:
        pdf.setFont("Helvetica", 8)
        pdf.setFillColor(colors.HexColor("#7a8699"))
        pdf.drawString(40, y - 8, f"Showing 12 of {len(chain_rows)} hops.")

    y -= 24
    y = _draw_section_title(pdf, "Investigator Notes", 40, y)
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.setFillColor(colors.HexColor("#7a8699"))
    pdf.drawString(40, y, "This report is auto-generated for internal review and does not replace")
    pdf.drawString(40, y - 12, "official FIU-IND filing procedures.")

    _draw_footer(pdf, width)

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    filename = f"fiu-ind-{evidence.txId}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
