"""
Streaming API endpoints for real-time alerts and model status.
"""

import asyncio
import os
from datetime import datetime, timezone
from typing import List

from fastapi import APIRouter, HTTPException, Header, WebSocket
from starlette.websockets import WebSocketDisconnect

from ...core.config import get_settings
from .schemas import AlertEvent, ModelStatus, AlertPayload, ModelStatusPayload

router = APIRouter(prefix="/api/v1/stream", tags=["stream"])


# Global alert queue shared with ML worker
alert_queue: asyncio.Queue = asyncio.Queue()


class ConnectionManager:
    """Manages WebSocket connections for alert streaming."""
    
    def __init__(self) -> None:
        self._connections: List[WebSocket] = []
        self._lock = asyncio.Lock()

    async def connect(self, websocket: WebSocket) -> None:
        """Add a new WebSocket connection."""
        await websocket.accept()
        async with self._lock:
            self._connections.append(websocket)

    async def disconnect(self, websocket: WebSocket) -> None:
        """Remove a WebSocket connection."""
        async with self._lock:
            if websocket in self._connections:
                self._connections.remove(websocket)

    async def broadcast(self, message: str) -> None:
        """Broadcast a message to all connected clients."""
        async with self._lock:
            connections = list(self._connections)

        for websocket in connections:
            try:
                await websocket.send_text(message)
            except (WebSocketDisconnect, RuntimeError):
                await self.disconnect(websocket)


manager = ConnectionManager()


async def alert_broadcaster():
    """
    Background task that reads from alert_queue and broadcasts to WebSocket clients.
    
    This task runs continuously and sends alerts to all connected WebSocket clients.
    """
    print("[Alert Broadcaster] Started")
    
    while True:
        try:
            # Wait for alert from queue
            alert = await alert_queue.get()
            
            # Convert to JSON and broadcast
            if isinstance(alert, dict):
                import json
                message = json.dumps(alert)
            else:
                message = alert.model_dump_json() if hasattr(alert, 'model_dump_json') else str(alert)
            
            await manager.broadcast(message)
            print(f"[Alert Broadcaster] Broadcasted alert: {alert.get('txId', 'unknown')}")
            
        except Exception as e:
            print(f"[Alert Broadcaster] Error: {str(e)}")
            await asyncio.sleep(1)


@router.websocket("/alerts")
async def alerts_websocket(websocket: WebSocket) -> None:
    """
    WebSocket endpoint for real-time alert streaming.
    
    Clients connect and receive alerts as they are generated by the ML worker.
    No authentication required for WebSocket (can be added via query params if needed).
    """
    await manager.connect(websocket)
    print(f"[WebSocket] Client connected. Total connections: {len(manager._connections)}")
    
    try:
        # Keep connection alive and listen for client messages (ping/pong)
        while True:
            # Wait for any message from client (or disconnect)
            await websocket.receive_text()
            
    except WebSocketDisconnect:
        await manager.disconnect(websocket)
        print(f"[WebSocket] Client disconnected. Total connections: {len(manager._connections)}")


@router.get("/model-status", response_model=ModelStatus)
async def get_model_status(
    x_api_key: str = Header(None)
) -> ModelStatus:
    """
    Get ML model status information.
    
    Returns:
    - last_trained: Timestamp of last training (from model file mtime)
    - model_file_exists: Whether the model file exists
    - total_scored: Number of transactions scored (from Neo4j)
    """
    settings = get_settings()
    if x_api_key != settings.API_KEY:
        raise HTTPException(status_code=401, detail="Invalid or missing API key")
    
    model_path = 'data/fraud_model.json'
    
    # Check if model file exists
    model_file_exists = os.path.exists(model_path)
    
    # Get last trained timestamp from file modification time
    last_trained = None
    if model_file_exists:
        mtime = os.path.getmtime(model_path)
        last_trained = datetime.fromtimestamp(mtime, tz=timezone.utc)
    
    # Get total scored from Neo4j
    from ...db.neo4j_client import get_driver
    
    try:
        driver = get_driver()
        with driver.session() as session:
            result = session.run("""
                MATCH (t:Transaction)
                WHERE t.risk_score > 0.0
                RETURN count(t) AS total_scored
            """).single()
            
            total_scored = int(result["total_scored"]) if result else 0
    except Exception as e:
        print(f"[Model Status] Error querying Neo4j: {str(e)}")
        total_scored = 0
    
    return ModelStatus(
        last_trained=last_trained,
        model_file_exists=model_file_exists,
        total_scored=total_scored
    )


# Legacy endpoints for backward compatibility
_alert_buffer: List[AlertPayload] = []
_model_status: ModelStatusPayload | None = None


def _store_alert(payload: AlertPayload, max_size: int = 50) -> None:
    """Store alert in buffer for legacy endpoint."""
    _alert_buffer.append(payload)
    if len(_alert_buffer) > max_size:
        _alert_buffer[:] = _alert_buffer[-max_size:]


def _store_model_status(payload: ModelStatusPayload) -> None:
    """Store model status for legacy endpoint."""
    global _model_status
    _model_status = payload


@router.post("/ingest")
async def ingest_alert(payload: AlertPayload, x_api_key: str = Header(None)) -> dict:
    """Legacy endpoint for ingesting alerts."""
    settings = get_settings()
    if x_api_key != settings.API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")

    _store_alert(payload)
    await manager.broadcast(payload.model_dump_json())
    return {"status": "ok"}


@router.post("/status")
async def ingest_status(payload: ModelStatusPayload, x_api_key: str = Header(None)) -> dict:
    """Legacy endpoint for ingesting model status."""
    settings = get_settings()
    if x_api_key != settings.API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")

    _store_model_status(payload)
    return {"status": "ok"}


@router.get("/status/latest", response_model=ModelStatusPayload | None)
async def latest_status() -> ModelStatusPayload | None:
    """Legacy endpoint for getting latest model status."""
    return _model_status
